# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bor < Formula
  desc "CLI issue tracker backed by GitHub Issues"
  homepage "https://github.com/jmaddaus/boxofrocks"
  version "3.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmaddaus/boxofrocks/releases/download/v3.1.0/bor-darwin-amd64.tar.gz"
      sha256 "b65192022df60f48ec594d3cb1aedaf738acb5c4064f5c6738d81698c40615db"

      def install
        bin.install "bor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmaddaus/boxofrocks/releases/download/v3.1.0/bor-darwin-arm64.tar.gz"
      sha256 "8851a44e8d79076fcc3585673a23674298c32057bdbc23bfdf9d635fab47a428"

      def install
        bin.install "bor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmaddaus/boxofrocks/releases/download/v3.1.0/bor-linux-amd64.tar.gz"
      sha256 "226acfc9d2fb4d2cb7d0e660d7fdfebc911f40800d820fae12995bc5384147d1"
      def install
        bin.install "bor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmaddaus/boxofrocks/releases/download/v3.1.0/bor-linux-arm64.tar.gz"
      sha256 "d7bd100a25fb742b8d653a450848eb815edbc639fbe03c1dfa0da93f4e9f3e3e"
      def install
        bin.install "bor"
      end
    end
  end
end
